### ISSUE TITLE
Tree expand collapse icons are not visible on selected line

### ISSUE THREAD

**Issue by gayanper** [Hecatoncheir/espresso_light_theme#3]
On Windows 10 when selecting the tree item cause the expand collapse icon not to be visible due to the selection background and the icon both having the color as white.

**Comment by rkrv** [comment]
👋   I'm having the same issue:

![image](https://user-images.githubusercontent.com/840660/89411752-9a92c980-d72e-11ea-98e9-e0b49952f1cf.png) 
![image](https://user-images.githubusercontent.com/840660/89411768-a1214100-d72e-11ea-99c2-306af9e605c8.png)

**Comment by Hecatoncheir** [comment]
I do not know what I can use for fix that:

![Annotation 2020-09-02 235339](https://user-images.githubusercontent.com/910917/92035719-cd54cf80-ed77-11ea-9f22-95333c2654c5.png)

Maybe later, when it will be possible...

**Comment by rkrv** [comment]
@Hecatoncheir I had it traced back to the `Espresso Light` theme using `IntelliJ Light` as the base for icons.

![image](https://user-images.githubusercontent.com/840660/92368236-228a3b80-f100-11ea-996b-163a2d7e3510.png)

I found that you should be able to replace default icons with custom icons in a theme, there is a readme here: https://jetbrains.org/intellij/sdk/docs/reference_guide/ui_themes/themes_customize.html

The icon names from the IntelliJ Light theme are: `arrowDown_dark`, `arrowDown_white`, `treeDownArrow`, (and could be others similar - I haven't been able to identify exactly which).

Default icons on osx live under `/Applications/PHPStorm/Contents/lib/icons.jar`.

Hope any of this helps.

**Comment by Hecatoncheir** [comment]
I use `Tree.iconColor`:

```
  "icons": {
    "ColorPalette": {
      "Tree.iconColor": "#325a7d",
```

But  expand/collapse icons work perfect only if "dark" property set true:

![Screenshot 2021-02-16 222616](https://user-images.githubusercontent.com/910917/108112037-9c0e5880-70a6-11eb-8c7b-b33754582c1d.png)

Not perfect theme system...

**Comment by Hecatoncheir** [comment]
Maybe like this(1.2.0 version):
![gnome-shell-screenshot-0OFD00](https://user-images.githubusercontent.com/910917/111427674-d599aa00-86cc-11eb-847a-950f837764f0.png)

**Comment by rkrv** [comment]
Just got the update, looks sweet!

**Comment by Hecatoncheir** [comment]
Thx.
